#!/bin/bash
touch README.md
echo "# // PROJECT NAME //

---
* // TITLE //
---
## Tasks
* Mandatory
- [ ] Task 0
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3
- [ ] Task 4
- [ ] Task 5
- [ ] Task 6
- [ ] Task 7
- [ ] Task 8
- [ ] Task 9

* Advanced
- [ ] Task 10
- [ ] Task 11
- [ ] Task 12
- [ ] Task 13
- [ ] Task 14
- [ ] Task 15" >> README.md
